language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "xiaoyufei"
  - git config user.email "915724526@qq.com"
  - git add .
  - git commit -m "build docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/XyyF/xiaojing0UI-dist.git
